title: About me
description: My personal profile
author: Roberto N.
email: oo.robert@yahoo.com
theme: hacker  # the Hacker theme
baseurl: ""    # User site
url: "https://robert1oo.github.io"  # URL of my GitHub Pages site

# Plugins to enhance the site
plugins:
  - jekyll-feed
  - jekyll-sitemap

